### ISSUE TITLE
Can this be used to write tests for a purely ROR application?

### ISSUE THREAD

**Issue by zaidsohail** [tyronewilson/protractor-rails#52]
Hey. Previously Ive only used Protractor for a AngularJS based web app, while obviously utilizing protractor's synchronization feature. Would I still be able to use this feature through this setup for my project's purely ROR app (no angular involved what so ever). Thanks, looking forward to your feedback :)

**Comment by tyronewilson** [comment]
I guess you could technically since Protractor is just a light wrapper around Selenium (as I understand it) but I personally wouldn't bother with this for a plain RoR app. I would just use [Capybara](https://github.com/teamcapybara/capybara) which has a much  nicer API and is for the most part much more stable to work with as well as integrating right in there with all of the rest of your Rspec tests.

So unless you come against something that really isn't working for you, use [Capybara](https://github.com/teamcapybara/capybara).

**Comment by zaidsohail** [comment]
My goal here is to automate the regression testing that we do each sprint (from a users perspective, involves field level validations and successfully creation/editing of certain entities) and to get a decent report of passed/failed tests after each execution. Would I be able to do this through Capybara?

And If you could answer one more thing, I would really appreciate. How steep would the learning curve be from Protractor to Capybara? Considering that I have previously fully automated regression testing for a purely AngularJS app (with CI using Jenkins). 

Thanks.

Sent from Mail for Windows 10
